name: Flask Back-end Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  APP_NAME: api-backend-flask

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        cd api-server
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

  DeployDev:
    name: Deploy to Dev 
    needs: [Build]
    runs-on: ubuntu-latest
    environment: 
      name: Development
      url: 'https://${{env.APP_NAME}}-dev.herokuapp.com/'
    steps:
      - name: Deploy
        run: echo I am deploying ${{ env.APP_NAME }} at https://${{env.APP_NAME}}-dev.herokuapp.com/
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "${{ env.APP_NAME }}-dev" #Must be unique in Heroku
          heroku_email: "${{ secrets.HEROKU_EMAIL }}"
          appdir: "api-server"
        env:
          HD_FLASK_ENV: ${{secrets.FLASK_ENV}}
          HD_DEVELOPMENT_KEY: ${{secrets.DEVELOPMENT_KEY}}